import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <div className="container d-flex flex-row justify-content-around">
            <div className='m-2 p-2 bg-primary'>Hello</div>
            <div className='m-2 p-2 bg-success'>Hello</div>
            <div className='m-2 p-2 bg-secondary'>Hello</div>
          </div>
        </div>
      </main>
    </>
  )
}
