import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Fhome.module.css'
import Carousel from 'react-bootstrap/Carousel';
import { HiOutlineBuildingOffice2 } from 'react-icons/hi'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main><br /><br /><br />
        <div className={`${styles.welcome}`}>
          <h1>Welcome to Heart Raiser</h1>
        </div><br /><br />
        <section className={`${styles.newwss}`}>
          <div className={`${styles.newsd}`}>
            <div className={`${styles.news}`}>
              <div className={`${styles.aa}`}>
                <Carousel controls={false} variant="dark" className={`${styles.pehla}`}>
                  <Carousel.Item className={`${styles.dfircaro}`} interval={1000}>
                    <img
                      className={`${styles.fircaro} d-block w-100`}
                      src="/1797971.jpg"
                      alt="First slide"
                    />
                  </Carousel.Item>
                  <Carousel.Item className={`${styles.dfircaro}`} interval={1000}>
                    <img
                      className={`${styles.fircaro} d-block w-100`}
                      src="/5640557.jpg"
                      alt="Second slide"
                    />
                  </Carousel.Item>
                  <Carousel.Item className={`${styles.dfircaro}`} interval={1000}>
                    <img
                      className={`${styles.fircaro} d-block w-100`}
                      src="/5591010.jpg"
                      alt="Third slide"
                    />
                  </Carousel.Item>
                </Carousel>
              </div>

              <Carousel variant="dark" className={`${styles.doosra}`}>
                <Carousel.Item className={`${styles.dcaro}`} interval={1000}>
                  <img
                    className={`${styles.caro} d-block w-100`}
                    src="/1797971.jpg"
                    alt="First slide"
                  />
                  <Carousel.Caption className={`${styles.newc}`}>
                    <h3>First slide label</h3>
                    <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
                  </Carousel.Caption>
                </Carousel.Item>
                <Carousel.Item className={`${styles.dcaro}`} interval={1000}>
                  <img
                    className={`${styles.caro} d-block w-100`}
                    src="/5640557.jpg"
                    alt="Second slide"
                  />
                  <Carousel.Caption className={`${styles.newc}`}>
                    <h3>Second slide label</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                  </Carousel.Caption>
                </Carousel.Item>
                <Carousel.Item className={`${styles.dcaro}`} interval={1000}>
                  <img
                    className={`${styles.caro} d-block w-100`}
                    src="/5591010.jpg"
                    alt="Third slide"
                  />
                  <Carousel.Caption className={`${styles.newc}`}>
                    <h3>Third slide label</h3>
                    <p>
                      Praesent commodo cursus magna, vel scelerisque nisl consectetur.
                    </p>
                  </Carousel.Caption>
                </Carousel.Item>
              </Carousel>


              <div className={`${styles.cc}`}>
                <Carousel controls={false} variant="dark" className={`${styles.tisra}`}>
                  <Carousel.Item className={`${styles.dseccaro}`} interval={1000}>
                    <img
                      className={`${styles.seccaro} d-block w-100`}
                      src="/1797971.jpg"
                      alt="First slide"
                    />
                  </Carousel.Item>
                  <Carousel.Item className={`${styles.dseccaro}`} interval={1000}>
                    <img
                      className={`${styles.seccaro} d-block w-100`}
                      src="/5640557.jpg"
                      alt="Second slide"
                    />
                  </Carousel.Item>
                  <Carousel.Item className={`${styles.dseccaro}`} interval={1000}>
                    <img
                      className={`${styles.seccaro} d-block w-100`}
                      src="/5591010.jpg"
                      alt="Third slide"
                    />
                  </Carousel.Item>
                </Carousel>
              </div>
            </div>
          </div>
        </section><br /><br /><hr className={`${styles.hr}`} />

        <section className={`${styles.About}`}>
          <div className={`${styles.abouthead}`}>
            <h1>About Us</h1><hr className={`${styles.hr}`} />
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos saepe ut nobis ex maxime, nihil non maiores, qui repellendus nemo optio doloribus culpa fuga vel cum. Vel illum dolores sapiente itaque consectetur explicabo vitae aliquid ducimus? Dolores maiores dicta exercitationem vitae nobis autem magnam. Numquam reiciendis vero consectetur laudantium voluptatum placeat id, deserunt quia repellendus odit accusamus quam. Ipsam quidem, dolorum ducimus nam magni vero earum repellendus libero fugiat, possimus dolores saepe architecto velit sequi voluptate vitae tempora, eveniet maxime consectetur quos? Reiciendis iusto deleniti rerum neque, aliquam ab deserunt consequatur reprehenderit ipsa totam porro officiis modi? Qui, asperiores inventore?</p>
          </div><br />

          <div className={`${styles.person}`}>
            <div className={`${styles.abhi0}`}>
              <div className={`${styles.abhi}`}>
                <div className={`${styles.img}`}></div>
                <div className={`${styles.about}`}>
                  <h3>Abhijeet Sahu</h3>
                  <p className={`${styles.work}`}>Front-end Developer (CSE 2nd Year, OUTR-25)</p>
                  <p>"Fundraising is the gentle art of teaching the joy of giving."</p>
                </div>
              </div>
            </div><br />
            <div className={`${styles.dev0}`}>
              <div className={`${styles.dev}`}>
                <div className={`${styles.aboutt}`}>
                  <h3>Dev Ashrit Behera</h3>
                  <p className={`${styles.work}`}>Full Stack Developer (CSE 2nd Year, OUTR-25)</p>
                  <p>"Alone we can do so little, together we can do so much."</p>
                </div>
                <div className={`${styles.img1}`}></div>
              </div>
            </div><br />
            <div className={`${styles.paras0}`}>
              <div className={`${styles.paras}`}>
                <div className={`${styles.img}`}></div>

                <div className={`${styles.about}`}>
                  <h3>Paras Singh Bhatia</h3>
                  <p className={`${styles.work}`}>Back-end Developer (CSE 2nd Year, OUTR-25)</p>
                  <p>"Buckle up if you want to bring change to the world."</p>
                </div>
              </div>
            </div><br />
            <div className={`${styles.om0}`}>
              <div className={`${styles.om}`}>
                <div className={`${styles.aboutt}`}>
                  <h3>Subham Parida</h3>
                  <p className={`${styles.work}`}>Frontend Developer, Designer (CSE 2nd Year, OUTR-25)</p>
                  <p>"Not all of us can do great things, but we can do small things with great love."</p>
                </div>
                <div className={`${styles.img1}`}></div>
              </div>
            </div>
          </div>
        </section>
        <section className="NGO">
          <Carousel indicators={false} variant="dark" className={`carousel-inner ${styles.subham}`}>
            <Carousel.Item interval={3000}>
              <div className={`row ${styles.rowOfNgo}`}>
                <div className={`${styles.card} col-lg-4`}>
                  <img src="./1797971.jpg" className="mx-auto mt-4 card-img-top" alt="..." />
                  <div className="card-body mt-4">
                    <h5 className="card-title">Card title</h5>
                    <p className="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                  </div>
                </div>
                <div className={`${styles.card} col-lg-4`}>
                  <img src="./1797971.jpg" className="mx-auto mt-4 card-img-top" alt="..." />
                  <div className="card-body mt-4">
                    <h5 className="card-title">Card title</h5>
                    <p className="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                  </div>
                </div>
                <div className={`${styles.card} col-lg-4`}>
                  <img src="./1797971.jpg" className="mx-auto mt-4 card-img-top" alt="..." />
                  <div className="card-body mt-4">
                    <h5 className="card-title">Card title</h5>
                    <p className="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                  </div>
                </div>
                <div className={`${styles.card} col-lg-4`}>
                  <img src="./1797971.jpg" className="mx-auto mt-4 card-img-top" alt="..." />
                  <div className="card-body mt-4">
                    <h5 className="card-title">Card title</h5>
                    <p className="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                  </div>
                </div>
              </div>
            </Carousel.Item>
            <Carousel.Item interval={3000}>
              <div className={`row ${styles.rowOfNgo}`}>
                <div className={`${styles.card} col-lg-4`}>
                  <img src="./1797971.jpg" className="mx-auto mt-4 card-img-top" alt="..." />
                  <div className="card-body mt-4">
                    <h5 className="card-title">Card title</h5>
                    <p className="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                  </div>
                </div>
                <div className={`${styles.card} col-lg-4`}>
                  <img src="./1797971.jpg" className="mx-auto mt-4 card-img-top" alt="..." />
                  <div className="card-body mt-4">
                    <h5 className="card-title">Card title</h5>
                    <p className="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                  </div>
                </div>
                <div className={`${styles.card} col-lg-4`}>
                  <img src="./1797971.jpg" className="mx-auto mt-4 card-img-top" alt="..." />
                  <div className="card-body mt-4">
                    <h5 className="card-title">Card title</h5>
                    <p className="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                  </div>
                </div>
                <div className={`${styles.card} col-lg-4`}>
                  <img src="./1797971.jpg" className="mx-auto mt-4 card-img-top" alt="..." />
                  <div className="card-body mt-4">
                    <h5 className="card-title">Card title</h5>
                    <p className="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                  </div>
                </div>
              </div>
            </Carousel.Item>
            <Carousel.Item interval={3000}>
              <div className={`row ${styles.rowOfNgo}`}>
                <div className={`${styles.card} col-lg-4`}>
                  <img src="./1797971.jpg" className="mx-auto mt-4 card-img-top" alt="..." />
                  <div className="card-body mt-4">
                    <h5 className="card-title">Card title</h5>
                    <p className="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                  </div>
                </div>
                <div className={`${styles.card} col-lg-4`}>
                  <img src="./1797971.jpg" className="mx-auto mt-4 card-img-top" alt="..." />
                  <div className="card-body mt-4">
                    <h5 className="card-title">Card title</h5>
                    <p className="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                  </div>
                </div>
                <div className={`${styles.card} col-lg-4`}>
                  <img src="./1797971.jpg" className="mx-auto mt-4 card-img-top" alt="..." />
                  <div className="card-body mt-4">
                    <h5 className="card-title">Card title</h5>
                    <p className="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                  </div>
                </div>
                <div className={`${styles.card} col-lg-4`}>
                  <img src="./1797971.jpg" className="mx-auto mt-4 card-img-top" alt="..." />
                  <div className="card-body mt-4">
                    <h5 className="card-title">Card title</h5>
                    <p className="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                  </div>
                </div>
              </div>
            </Carousel.Item>
          </Carousel>
        </section>

        <section className="WHY">
          <div className={`${styles.h}`}><h1>Why Us</h1></div>
          <br /><br />
          <div className={`row ${styles.one} space`}>
            <div className={`${styles.whyUs} col-lg-4 col-md-4`}>
              <div className={`my-3 ${styles.why}`}>We are directly associated with the NGOs globally. NGOs can raise funds in our platform directly and people now can donate directly to NGOs through our platform.</div>
            </div>
            <div className={`${styles.whyUs} col-lg-4 col-md-4`}>
              <i className="fa-solid fa-tent-arrow-left-right"></i>
              <div className={`my-3 ${styles.why}`}>Transaction end to end facility provided here. Now directly communicate and keep raising Hearts.</div>
            </div>
            <div className={`${styles.whyUs} col-lg-4 col-md-4`}>
              <i className="fa-solid fa-hand-holding-dollar"></i>
              <div className={`my-3 ${styles.why}`}>Starting a fundraiser on HeartRaiser is absolutely free.</div>
            </div>
          </div>

          <div className={`row ${styles.two} space`}>
            <div className={`${styles.whyUs} col-lg-4 col-md-4`}>
              <i className="fa-solid fa-user-group"></i>
              <div className={`my-3 ${styles.why}`}>User friendly platform with a user friendly Dashboard.</div>
            </div>
            <div className={`${styles.whyUs} col-lg-4 col-md-4`}>
              <i className="fa-solid fa-shield-halved"></i>
              <div className={`my-3 ${styles.why}`}>Enhanced security To Ensure Trust & Safety, froads, etc. Now doante/raise without thinking twice.</div>
            </div>
            <div className={`${styles.whyUs} col-lg-4 col-md-4`}>
              <i className="fa-solid fa-heart-circle-plus"></i>
              <div className={`my-3 ${styles.why}`}>Reward points in the form of Hearts provided. Now the higher you get hearts, you get a badge along with a Certificate in the form of love and appreciation.</div>
            </div>
          </div>

          <div className={`row ${styles.three} space`}>
            <div className={`${styles.whyUs} col-lg-4 col-md-4`}>
              <i className="fa-solid fa-credit-card"></i>
              <div className={`my-5 ${styles.why}`}>Accepts donations all cards, netbanking, UPI and online wallets.</div>
            </div>
            <div className={`${styles.whyUs} col-lg-4 col-md-4`}>
              <i className="fa-sharp fa-solid fa-phone-volume"></i>
              <div className={`my-5 ${styles.why}`}>Reach out to us anytime with your queries. We are available for assistance 24x7.</div>
            </div>
            <div className={`${styles.whyUs} col-lg-4 col-md-4`}>
              <i className="fa-solid fa-bullseye"></i>
              <div className={`my-5 ${styles.why}`}>Your mission is our mission. So, let's make it happen and make it a revolution.</div>
            </div>
          </div>
        </section><br /><br /><br />

      </main>
    </>
  )
}
